"""Generate only the larger Okinawa tutorial layout (requires Shapely 2.1.2)."""
from pathlib import Path
import json
import math
import subprocess
from shapely import make_valid
from shapely.geometry import Polygon, box
from shapely.ops import unary_union

ROOT = Path(__file__).resolve().parents[1]
source = """
import fs from 'node:fs';
import {Geography} from './geometry.js';
import {BLOCK_LAYOUTS} from './block-layouts.js';
const geo=new Geography(JSON.parse(fs.readFileSync('./japan.json')));
console.log(JSON.stringify({shape:geo.stageShape(47),original:BLOCK_LAYOUTS[47]}));
"""
data = json.loads(subprocess.check_output(
    ['node', '--input-type=module', '-e', source], cwd=ROOT, text=True))

def polygons(geometry):
    if geometry.is_empty:
        return []
    if geometry.geom_type == 'Polygon':
        return [geometry]
    return [p for g in geometry.geoms for p in polygons(g)] if hasattr(geometry, 'geoms') else []

def ring(coords):
    return [[round(x, 5), round(y, 5)] for x, y in coords]

land = unary_union([p for rings in data['shape']['polygons']
                    for p in polygons(make_valid(Polygon(rings[0], rings[1:])))])
original = data['original']
cell = original['cell'] * 2
core = {**original['core'], 'r': original['core']['r'] * 2,
        'shieldR': 0, 'hp': 1, 'slot': [0, 0]}
cx, cy = core['x'], core['y']
x0, y0, x1, y1 = land.bounds
blocks = []
for row in range(math.floor((y0-cy)/cell), math.ceil((y1-cy)/cell)+1):
    for col in range(math.floor((x0-cx)/cell), math.ceil((x1-cx)/cell)+1):
        if row == 0 and col == 0:
            continue
        x, y = cx + col*cell, cy + row*cell
        rect = box(x-cell*.46, y-cell*.46, x+cell*.46, y+cell*.46)
        for part in sorted(polygons(land.intersection(rect)), key=lambda p: (p.bounds[1], p.bounds[0], p.area)):
            bx, by, bxx, byy = part.bounds
            if part.area < max(2, cell*cell*.02) or min(bxx-bx, byy-by) < 1:
                continue
            anchor = part.representative_point()
            blocks.append({'rings': [ring(part.exterior.coords)] + [ring(r.coords) for r in part.interiors],
                           'icon': [round(anchor.x, 5), round(anchor.y, 5)], 'area': round(part.area, 5),
                           'edge': not land.covers(rect), 'slot': [row, col]})
layout = {'cell': cell, 'core': core, 'blocks': blocks}
asset = '// Generated by scripts/prepare-okinawa.py; geographic sources: credits.html.\n'
asset += 'export const OKINAWA_LAYOUT=' + json.dumps(layout, separators=(',', ':')) + ';\n'
(ROOT/'okinawa-layout.js').write_text(asset, encoding='utf-8')
print(f'Okinawa: {len(blocks)} blocks, cell {cell}, core diameter {core["r"]*2}, one hit.')
