import {Geography,bounds,clamp} from './geometry.js';
import {Game,WIDTH,HEIGHT} from './engine.js';
import {CHAPTER_NAMES,CHAPTER_LINES,NEW_SAVE,validateSave,chapterIndex,availableIds,recordClear} from './progression.js';
import {Painter,prefectureColor,smallShape,svgPath,drawPaddle,drawDial,fitCanvas} from './paint.js';

import {bindRotation} from './rotation.js';

const root=document.getElementById('app'),KEY='kenken-breaker-save-v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clock=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
let geo,save=NEW_SAVE(),view='map',selected=47,selectedChapter=0,game=null,painter=null,paused=false,modal=null,angle=0,stopSpin=()=>{},replayOriginal=false,prepFinale=false,acc=0,last=0,lastSave=0,lastHUD='',audioContext=null,toastTimer;
let storageWarning=false,migratedRun=false;
try{const raw=localStorage.getItem(KEY);if(raw){const previous=JSON.parse(raw);save=validateSave(previous);migratedRun=!!previous.current&&!save.current;}}catch{storageWarning=true;}

function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));return true;}catch{if(!storageWarning){toast('このブラウザに保存できません。設定からセーブを書き出せます。');storageWarning=true;}return false;}}
function saveCurrent(){if(game&&!game.practice&&!['won','lost'].includes(game.status))save.current=game.snapshot();persist();}
function toast(text){document.querySelector('.toast')?.remove();clearTimeout(toastTimer);const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=text;document.body.append(el);toastTimer=setTimeout(()=>el.remove(),4200);}
function sound(type){if(!save.options.sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain(),now=audioContext.currentTime;const freq={launch:440,bounce:230,hit:650,core:940,miss:130,shield:1280,win:1150,extra:880,'barrier-on':620,'barrier-save':720}[type]||550;o.type=type==='miss'?'sine':'triangle';o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(type==='miss'?65:freq*1.22,now+.1);g.gain.setValueAtTime(.035,now);g.gain.exponentialRampToValueAtTime(.001,now+.16);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(now+.17);}catch{}}
function closeModal(){if(modal){modal.close();modal.remove();modal=null;}}
function dialog(html,{locked=false,variant=''}={}){closeModal();modal=document.createElement('dialog');modal.className=`dialog ${variant?`dialog-${variant}`:''}`;modal.innerHTML=html;modal.addEventListener('cancel',e=>{if(locked)e.preventDefault();else closeModal();});document.body.append(modal);modal.showModal();}
function shell(content,active='map'){return `<div class="shell"><header class="topbar"><button class="wordmark" data-action="map" aria-label="日本地図へ"><img class="title-logo" src="./assets/title-logo.png" width="2032" height="774" alt="進撃の沖縄県 — 都道府県ブロック崩し" fetchpriority="high"></button><nav class="topnav" aria-label="メイン"><button data-action="map" class="${active==='map'?'active':''}">地図</button><button data-action="book" class="${active==='book'?'active':''}">図鑑</button><button data-action="settings" class="${active==='settings'?'active':''}">設定</button></nav></header>${content}</div>`;}
function pageTitle(eyebrow,title){return `<div class="page-top"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1></div><div class="progress-stat"><small>沖縄県の大きさ</small><strong>${save.cleared.length}</strong><span> / 47</span><div class="progress-line"><i style="width:${save.cleared.length/47*100}%"></i></div></div></div>`;}
function mapSVG(){
 const pts=[...geo.byId.values()].flatMap(p=>p.rings.flat(2).map(q=>geo.project(q))),b=bounds(pts),s=Math.min(405/(b.maxX-b.minX),398/(b.maxY-b.minY));
 const f=q=>{const [x,y]=geo.project(q);return [230+(x-(b.minX+b.maxX)/2)*s,217+(y-(b.minY+b.maxY)/2)*s];};
 const open=availableIds(geo,save.cleared),selectedPref=geo.get(selected),c=f(selectedPref.capitalPoint);
 const acquiredPath=save.cleared.map(id=>f(geo.get(id).capitalPoint));
 return `<svg class="map-art" viewBox="0 0 460 460" role="img" aria-label="47都道府県の攻略地図"><g>${[...geo.byId.values()].map(p=>`<g class="map-hit" data-pref="${p.id}"><title>${p.fullName} ${save.cleared.includes(p.id)?'クリア済み':open.includes(p.id)?'攻略できる':'未開放'}</title><path style="--pref-color:${prefectureColor(p.id)}" class="land ${save.cleared.includes(p.id)?'cleared':''} ${open.includes(p.id)?'available':''} ${selected===p.id?'selected':''}" d="${svgPath(p.rings,f)}" fill-rule="evenodd"/></g>`).join('')}</g>${acquiredPath.length>1?`<path d="${acquiredPath.map((p,i)=>`${i?'L':'M'}${p.join(',')}`).join('')}" stroke="#6dbfb780" stroke-width="1" stroke-dasharray="3 5" fill="none" pointer-events="none"/>`:''}<g data-pref="${selected}" class="map-hit"><circle cx="${c[0]}" cy="${c[1]}" r="15" fill="#ff666a15" stroke="#ff8680" stroke-width="1"/><circle cx="${c[0]}" cy="${c[1]}" r="4" fill="#ff7477"/><path d="M${c[0]+13},${c[1]}h26" stroke="#dc845b"/><text x="${clamp(c[0]+44,38,404)}" y="${c[1]+5}" fill="#226376" font-size="15" font-weight="700" stroke="#f4ffff" stroke-width="4" paint-order="stroke">${selectedPref.name}</text></g></svg>`;
}
function drawBoat(canvasId,ids=save.cleared,highlight=0,chosen=0){const c=document.getElementById(canvasId);if(!c)return;const ctx=fitCanvas(c,270,115),p=geo.makePaddle(ids,ids.length?chosen:0);drawPaddle(ctx,p,135,55,geo,{scale:Math.min(1.5,48/p.radius),highlight});}
function animateAcquisition(id,chosen){const c=document.getElementById('result-paddle');if(!c||save.options.reduced)return;const ctx=fitCanvas(c,270,115),p=geo.makePaddle(save.cleared,chosen),start=performance.now();const animate=now=>{if(!c.isConnected)return;const t=clamp((now-start)/1400,0,1),reveal=1-(1-t)**3;ctx.clearRect(0,0,270,115);drawPaddle(ctx,p,135,55,geo,{scale:Math.min(1.5,48/p.radius),highlight:id,reveal});if(t<1)requestAnimationFrame(animate);};requestAnimationFrame(animate);}
function renderMap(){
 view='map';paused=false;const p=geo.get(selected),open=availableIds(geo,save.cleared),done=save.cleared.includes(selected),can=done||open.includes(selected),ch=chapterIndex(geo,save.cleared);
 const note=ch<0?'日本まるごと、沖縄県になった。好きな県へ、もう一度。':selectedChapter>ch?`${CHAPTER_NAMES[selectedChapter-1]}を制覇すると、この地方へ進めます。`:'獲得済みの県に隣り合う県から、次の行き先を選べます。';
 root.innerHTML=shell(`${save.current?`<div class="resume-banner"><span>${geo.get(save.current.id)?.name||'旅'}の途中で中断しています</span><button data-action="resume">つづきから</button></div>`:''}${pageTitle('次の県を選ぼう','全国吸収マップ')}<p class="story-intro">吸収するほど巨大化。日本まるごと、沖縄県へ。</p><div class="chapter-strip" aria-label="地方を選ぶ">${CHAPTER_NAMES.map((n,i)=>`<button class="chapter-chip ${i===ch?'current':''} ${i===selectedChapter?'selected':''}" data-chapter="${i}">${n}<small>${geo.chapters[i].filter(id=>save.cleared.includes(id)).length}/${geo.chapters[i].length}</small></button>`).join('')}</div><div class="journey"><div><div class="map-panel"><div class="map-grid"></div><div class="compass">N<br><b>↑</b></div>${mapSVG()}<div class="map-label">吸収エリア / ${String(Math.max(0,ch)+1).padStart(2,'0')}</div><div class="map-legend"><span><i style="background:#ffe15b"></i>攻略できる</span><span><i style="background:#30d6b2"></i>クリア済み</span><span><i style="background:#c7dfed;border:1px solid #698ca8"></i>未開放</span></div></div><div class="province-list" aria-label="${CHAPTER_NAMES[selectedChapter]}の都道府県">${geo.chapters[selectedChapter].map(id=>`<button data-pref="${id}" class="province ${open.includes(id)?'open':''} ${save.cleared.includes(id)?'done':''} ${selected===id?'selected':''}">${save.cleared.includes(id)?'✓ ':''}${geo.get(id).name}</button>`).join('')}</div><p class="route-note">${note}</p></div><aside class="aside"><section class="stage-card"><p class="eyebrow">${selected===47&&!done?'はじめの一歩':done?'もう一度挑戦':selected===1?'最後の吸収ターゲット':'吸収ターゲット'} / ${CHAPTER_NAMES[p.chapter]}</p><div class="stage-heading"><h2>${p.name}</h2><div class="shape" style="color:${prefectureColor(selected)}">${smallShape(geo,selected)}</div></div><div class="capital"><i class="core-dot"></i>核の位置：${p.capital}</div><p class="desc">${can?(selected===47&&!done?'はじめは横棒。大きな赤い核に1回当てよう！':'海岸線を使って、赤い核へ。黄色の＋1と水色のバリアが助っ人。'):'ほかの県をクリアすると、ここへ進めます。'}</p><button class="primary" data-action="prep" ${can?'':'disabled'}>${done?'もう一度挑む':can?selected===47?'沖縄県、進撃開始！':`${p.name}を吸収する`:'まだ行けません'}</button></section><section class="boat-card"><header><span class="boat-title">いまの沖縄県</span> <span class="size-badge">${save.cleared.length?`${save.cleared.length}県ぶん`:'一本の横棒'}</span></header><canvas id="boat-preview" aria-label="獲得した県でできた現在のパドル"></canvas><p>${save.cleared.length?'吸収した県の色と形が、そのまま体に。':'沖縄をクリアすると、沖縄の形に！'}</p></section>${ch<0?'<button class="secondary" data-action="finale-prep">列島フィナーレで遊ぶ</button>':''}</aside></div><div class="footer-help"><button data-action="help">遊び方</button><span>進行は自動保存</span></div>`);
 drawBoat('boat-preview');
}
function paddleIds(){if(prepFinale)return save.cleared;if(replayOriginal&&save.cleared.includes(selected))return save.cleared.slice(0,save.cleared.indexOf(selected));return save.cleared;}
function goPrep({skipStory=false,keepAngle=false,finale=false}={}){
 if(save.current&&!keepAngle&&!skipStory){dialog('<h2>中断中のゲームがあります</h2><p>新しくスタートすると、ステージ途中の記録が置き換わります。獲得した県は残ります。</p><button class="primary" data-action="replace-run">新しくあそぶ</button><button class="secondary" data-action="resume">つづきから</button><button class="quiet" data-action="close">戻る</button>');return;}
 prepFinale=finale;
 const ch=geo.get(selected).chapter;
 if(!skipStory&&!finale&&!save.seenChapters.includes(ch)){
  dialog(`<p class="eyebrow">CHAPTER ${String(ch+1).padStart(2,'0')} / ${CHAPTER_NAMES[ch]}</p><h2>${ch===0?'沖縄県、巨大化を決意。':ch===8?'ついに、でっかい北海道！':`${CHAPTER_NAMES[ch]}まで来たぞ！`}</h2><p>${CHAPTER_LINES[ch]}</p><button class="primary" data-action="story-next">角度を決める</button>`);return;
 }
 if(!keepAngle)angle=0;replayOriginal=false;renderPrep();
}
function renderPrep(){view='prep';closeModal();const p=geo.get(selected);
 root.innerHTML=shell(`<main class="page-narrow prep-page"><div class="backline"><button class="quiet" data-action="map">← 地図へ</button><span class="badge">${save.options.easy?'ゆっくり':'通常'}</span></div><div class="prep-layout"><section class="prep-summary"><div><p class="eyebrow">${prepFinale?'フィナーレ':`吸収ターゲット / ${CHAPTER_NAMES[p.chapter]}`}</p><h2>${prepFinale?'列島フィナーレ':p.fullName}</h2><div class="capital"><i class="core-dot"></i>${prepFinale?'47の形で、最後のひと遊び':`${p.capital}の核`}</div><p class="subtle" style="margin-top:12px">${prepFinale?'60秒間、落球しても続きます。':selected===47?'シールドなし。赤い核に1回当てればクリア！':'1回目でシールド、2回目で赤い核を壊そう。'}</p></div><div class="shape" style="color:${prefectureColor(selected)}">${smallShape(geo,selected)}</div></section><section><div class="prep-title"><h1>角度を決めよう</h1><output id="angle-value" class="angle-number">${Math.round(angle)%360}°</output></div><div class="dial-wrap"><canvas id="angle-preview" aria-label="スワイプしてパドルを回転。北が上で0度。"></canvas></div><div class="angle-controls"><button data-action="rotate-left" aria-label="左へ90度回転">↶</button><input id="angle-slider" type="range" min="0" max="359" step="1" value="${angle}" aria-label="パドルの角度"><button data-action="rotate-right" aria-label="右へ90度回転">↷</button></div><div class="angle-reset-row"><span>北が上で 0°</span><button class="quiet" data-action="reset-angle">↑ 北を上に戻す</button></div><p class="prep-note">指でスワイプすると、くるくる回ります。<br>プレイ中は、この角度で固定！</p>${save.cleared.includes(selected)&&!prepFinale?`<div class="prep-options"><label for="replay-shape">パドルの形</label><select id="replay-shape"><option value="current" ${!replayOriginal?'selected':''}>現在のパドル</option><option value="original" ${replayOriginal?'selected':''}>この県に初めて挑んだときのパドル</option></select></div>`:''}<div class="item-legend"><span><b class="extra-icon">+1</b>ボールが1個増える</span><span><b class="barrier-icon"><svg width="14" height="16" viewBox="0 0 16 18" aria-hidden="true"><path d="M2 2H14L13 11L8 16L3 11Z" fill="none" stroke="currentColor" stroke-width="1.7"/></svg></b>落下を1回ガード</span></div><div class="prep-actions"><button class="secondary" data-action="practice">試し打ち</button><button class="primary" data-action="start">この角度であそぶ</button></div><p class="instruction">${prepFinale?'':`${selected===47?'赤い核に1回当てればクリア！':'1回目でシールド、2回目で赤い核を破壊！'}<br>ほかのブロックは残っていてもクリア。`}</p></section></div></main>`);
 updateDial();bindDial();
}
function updateDial(){angle=((angle%360)+360)%360;const out=document.getElementById('angle-value'),slider=document.getElementById('angle-slider');if(out)out.textContent=`${Math.round(angle)%360}°`;if(slider)slider.value=angle;const c=document.getElementById('angle-preview');if(c)drawDial(c,geo.makePaddle(paddleIds(),angle),geo);}
function bindDial(){stopSpin();const c=document.getElementById('angle-preview');if(c)stopSpin=bindRotation(c,{getAngle:()=>angle,setAngle:a=>{angle=a;updateDial();},reducedMotion:save.options.reduced||window.matchMedia('(prefers-reduced-motion: reduce)').matches});}
function startGame(practice=false,snapshot=null){
 stopSpin();closeModal();sound('launch');const id=snapshot?.id??selected;selected=id;
 try{
  const opts=snapshot?{id,cleared:save.cleared,angle:snapshot.angle,easy:snapshot.easy,finale:!!snapshot.finale,paddleIds:validatedPaddleIds(snapshot.paddleIds),snapshot}:{id,cleared:save.cleared,paddleIds:paddleIds(),angle,easy:save.options.easy,practice,finale:prepFinale};
  if(snapshot&&(!Number.isFinite(snapshot.angle)||snapshot.angle<0||snapshot.angle>=360))throw new Error('中断した角度を読み込めませんでした。');
  game=new Game(geo,opts);
 }catch(e){game=null;save.current=null;persist();toast(e.message);renderMap();return;}
 if(!practice&&!snapshot){save.angles[id]=angle;save.current=game.snapshot();persist();}
 view='game';paused=false;acc=0;lastHUD='';renderGame();if(snapshot){paused=true;pauseDialog(true);}
}
function validatedPaddleIds(ids){if(!Array.isArray(ids)||ids.length>47||ids.some(id=>!Number.isInteger(id)||!geo.get(id)))throw new Error('パドルの中断データが不正です。');return [...new Set(ids)];}
function renderGame(){const p=geo.get(game.id);root.innerHTML=`<main class="game-shell"><header class="game-header"><div><h1>${game.finale?'列島フィナーレ':p.fullName}</h1><p class="subtle">${game.practice?'試し打ち':game.finale?'進撃の沖縄県':`吸収ターゲット / ${p.capital}`}</p></div><button class="pause-button" data-action="pause" aria-label="一時停止">Ⅱ</button></header><div class="game-hud"><div class="hud-core"><i class="core-dot"></i><span id="core-hud"></span></div><span class="hud-life" id="life-hud"></span><span class="subtle">${Math.round(game.angle)%360}°</span></div><div class="board-wrap"><canvas id="game-canvas" width="400" height="600" aria-label="ブロック崩し。左右ドラッグまたは矢印キーで移動。スペースで発射。"></canvas><button id="launch-button" class="launch-button" data-action="launch">発射！</button></div><div class="game-controls"><div class="touch-strip" id="touch-strip" aria-label="左右にドラッグしてパドルを動かす">← 沖縄県を左右に動かす →</div></div><div class="game-foot" id="item-hud">${game.practice?'試し打ちの結果は記録されません':'島の隙間は、球が通り抜けます'}</div></main>`;
 painter=new Painter(document.getElementById('game-canvas'),game,save.options);painter.draw();bindGameInput();updateHUD();
}
function bindGameInput(){let drag=null;const handleDown=e=>{if(paused)return;const el=e.currentTarget;el.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,start:game.targetX,moved:false};};const handleMove=e=>{if(!drag||drag.id!==e.pointerId||paused)return;const c=document.getElementById('game-canvas'),b=c.getBoundingClientRect(),dx=(e.clientX-drag.x)*WIDTH/b.width*save.options.sensitivity;if(Math.abs(dx)>5)drag.moved=true;game.setTarget(drag.start+dx);};const handleUp=e=>{if(drag&&!drag.moved&&game.status==='ready'&&!paused)game.launch();drag=null;};for(const id of ['game-canvas','touch-strip']){const e=document.getElementById(id);e.addEventListener('pointerdown',handleDown);e.addEventListener('pointermove',handleMove);e.addEventListener('pointerup',handleUp);e.addEventListener('pointercancel',()=>drag=null);}}
const keys=new Set();window.addEventListener('keydown',e=>{if(view!=='game'||modal)return;if(['ArrowLeft','ArrowRight',' ','Escape'].includes(e.key))e.preventDefault();keys.add(e.key);if(e.key===' '&&!paused)game.launch();if(e.key==='Escape')pauseDialog();});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{keys.clear();if(view==='game'&&!paused&&!['won','lost'].includes(game?.status))pauseDialog(true);});
function updateHUD(){if(view!=='game'||!game)return;const signature=[game.core.hp,game.lives,game.status,game.balls.length,game.barrierActive].join(':');if(signature===lastHUD)return;lastHUD=signature;
 document.getElementById('core-hud').textContent=game.finale?'花火を打ち上げよう':game.core.hp===2?'シールドあり':game.core.hp===1?(game.id===47?'核に1回当てよう！':'あと1回！'):'クリア！';
 document.getElementById('life-hud').textContent=game.practice||game.finale||game.id===47?'残り ∞':`残り ${'●'.repeat(game.lives)}`;
 document.getElementById('item-hud').textContent=`ボール ${game.balls.length}個${game.barrierActive?'　｜　バリア 1回':''}${game.practice?'　｜　おためし中':''}`;
 document.getElementById('launch-button').classList.toggle('hidden',game.status!=='ready'||paused);

}
function pauseDialog(fromBackground=false){if(!game||['won','lost'].includes(game.status))return;paused=true;keys.clear();saveCurrent();lastHUD='';updateHUD();dialog(`<p class="eyebrow">PAUSED</p><h2>ひと休み</h2><p>${game.practice?'試し打ちを一時停止しています。':fromBackground?'ゲームを中断しました。準備ができたら再開できます。':'この地点から、いつでも再開できます。'}</p><button class="primary" data-action="unpause">ゲームを再開</button>${game.practice?'<button class="secondary" data-action="practice-back">角度を選び直す</button>':`<button class="secondary" data-action="game-map">中断して地図へ</button>`}<button class="secondary" data-action="recall">${game.id===47||game.practice||game.finale?'球を戻して再発射':'1球使って再発射'}</button><button class="quiet" data-action="restart-confirm">最初から角度を選び直す</button>`,{locked:true});}
function handleGameEvent(e){painter?.event(e);if(['hit','bounce','shield','core','miss','win','extra','barrier-on','barrier-save'].includes(e.type))sound(e.type);if(e.type==='lost')showLost();if(e.type==='win')onWin();}
function showLost(){paused=true;if(!game.practice){save.current=null;persist();}dialog(`<p class="eyebrow">TRY AGAIN</p><h2>構えを変えて、もう一度。</h2><p>獲得した県は、そのまま残っています。使う海岸線を変えると、反射も変わります。</p><button class="primary" data-action="retry">角度を選び直す</button><button class="secondary" data-action="retry-same">同じ角度で再挑戦</button><button class="secondary" data-action="retry-easy">球をゆっくりにして再挑戦</button><button class="quiet" data-action="game-map">地図へ</button>`,{locked:true});}
function afterClear(render){const finished=game;setTimeout(()=>{if(view==='game'&&game===finished)render();},save.options.reduced?180:1050);}
function onWin(){
 paused=true;const g=game;
 if(g.practice){afterClear(()=>dialog('<p class="eyebrow">NICE SHOT!</p><h2>核に当たった！</h2><p>この角度、いいかも？ ほかの角度も試せます。</p><button class="primary" data-action="practice-back">準備に戻る</button>',{locked:true,variant:'result'}));return;}
 if(g.finale){save.finaleSeen=true;save.current=null;persist();afterClear(showEnding);return;}
 const before=save.cleared.length,chBefore=chapterIndex(geo,save.cleared);
 const result={time:g.time,noMiss:g.misses===0,timed:g.time<=(g.id===47?90:g.id===1?360:180),easy:g.easy,angle:g.angle,broken:g.broken,total:g.blocks.length};
 const first=recordClear(save,g.id,result);persist();
 const newChapter=chapterIndex(geo,save.cleared),p=geo.get(g.id);
 const line=g.id===47&&first?'沖縄県の形、完成。ここから巨大化だ！':g.id===1?'北海道まで吸収完了。日本、ぜんぶ沖縄県！':newChapter!==chBefore?'ひと地方まるごと吸収！ まだまだ大きくなるぞ！':first?'吸収完了。ひと県ぶん、大きくなったぞ！':'この形、すっかり使いこなしたぞ！';
 afterClear(()=>{
  dialog(`<p class="eyebrow result-banner">${g.id===47?'沖縄県、誕生！':first?'吸収成功！':'STAGE CLEAR!'}</p><h2>${g.id===47?'沖縄県、完成！':first?`${p.name}、吸収！`:`${p.name}、クリア！`}</h2><p class="story-quote">沖縄県「${line}」</p><canvas class="result-paddle" id="result-paddle" aria-label="${p.name}が加わったパドル"></canvas><div class="result-stats"><div><small>クリアタイム</small><strong>${clock(g.time)}</strong></div><div><small>${first?'沖縄県の大きさ':'ブロック破壊'}</small><strong>${first?`${before} → ${save.cleared.length}`:`${g.broken} / ${g.blocks.length}`}</strong></div></div><div class="achievements">✓ 核を破壊${result.noMiss?'　★ 落球なし':''}${result.timed?'　★ スピードクリア':''}</div>${newChapter!==chBefore&&newChapter>=0?`<p>次は${CHAPTER_NAMES[newChapter]}へ行けるよ！</p>`:''}<button class="primary" data-action="${g.id===1&&save.cleared.length===47?'ending':'next-map'}">${g.id===1&&save.cleared.length===47?'巨大化の結末を見る':'次の県を吸収する'}</button>`,{locked:true,variant:'result'});
  drawBoat('result-paddle',save.cleared,first?g.id:0,g.angle);if(first)animateAcquisition(g.id,g.angle);
 });
}
function showEnding(){dialog(`<p class="eyebrow">進撃の沖縄県、完結</p><h2>日本まるごと、沖縄県。</h2><p class="story-quote">沖縄県「ちょっと大きくなりすぎたかも。」</p><p>北海道まで吸収して、47の形がひとつの体に。<br>日本列島サイズの沖縄県が、ここに誕生した。<br>県庁は、たぶん那覇のままです。</p><canvas id="ending-paddle" class="result-paddle" aria-label="47都道府県を吸収した沖縄県"></canvas><button class="primary" data-action="next-map">地図にもどる</button><button class="quiet" data-action="finale-prep">巨大な体で、もうひと遊び</button>`,{locked:true,variant:'result'});drawBoat('ending-paddle');}
function renderBook(){view='book';root.innerHTML=shell(`${pageTitle('巨大化の記録','吸収コレクション')}<div class="book-grid">${[...geo.byId.values()].map(p=>{const done=save.cleared.includes(p.id),r=save.records[p.id]?.[save.options.easy?'easy':'normal'];return `<button style="--pref-color:${prefectureColor(p.id)}" class="book-card ${done?'collected':''}" data-book="${p.id}" aria-label="${p.fullName}${done?'の記録':' 未クリア'}"><div class="shape">${smallShape(geo,p.id)}</div><strong>${p.name}</strong><span>${done?p.capital:'未クリア'}</span><span class="stars">${done?'★':''}${r?.noMiss?'★':''}${r?.timed?'★':''}${!done?'—':''}</span></button>`;}).join('')}</div>`,'book');}
function showCard(id){const p=geo.get(id),done=save.cleared.includes(id),r=save.records[id]?.[save.options.easy?'easy':'normal'];dialog(`<p class="eyebrow">${CHAPTER_NAMES[p.chapter]} / ${String(id).padStart(2,'0')}</p><h2>${p.fullName}</h2><div style="max-width:210px;margin:10px auto;color:${done?prefectureColor(id):'#9ab8c3'}">${smallShape(geo,id,210,160)}</div><p>核の位置：${p.capital}</p>${done?`<p>${save.cleared.indexOf(id)+1}番目に獲得したかたち。</p>${r?`<div class="result-stats"><div><small>${save.options.easy?'ゆっくり':'通常'}のベスト</small><strong>${clock(r.time)}</strong></div><div><small>そのときの角度</small><strong>${Math.round(r.angle)}°</strong></div></div><p>ブロック破壊：${r.broken} / ${r.total}</p>`:''}<button class="primary" data-card-replay="${id}">この県にもう一度挑む</button>`:'<p>この県をクリアすると、旅の記録が残ります。</p>'}<button class="secondary" data-action="close">閉じる</button>`);}
function renderSettings(){view='settings';const opt=save.options;root.innerHTML=shell(`<main class="page-narrow">${pageTitle('SETTINGS','ゲームの設定')}<section class="settings-section">${[['sound','音','反射音と、核を砕く音。'],['easy','球をゆっくりにする','次のスタートから適用。地形と反射のルールは同じ。'],['reduced','演出を控えめにする','粒子と光の点滅を減らす。']].map(([key,name,desc])=>`<label class="setting"><span><strong>${name}</strong><small>${desc}</small></span><input type="checkbox" data-option="${key}" ${opt[key]?'checked':''} aria-label="${name}"></label>`).join('')}<label class="setting"><span><strong>操作の感度</strong><small id="sensitivity-label">${opt.sensitivity.toFixed(1)}倍</small></span><input id="sensitivity" type="range" min="0.5" max="2.5" step="0.1" value="${opt.sensitivity}" aria-label="操作の感度"></label></section><h2 style="font-size:20px">セーブデータ</h2><p class="subtle" style="margin-top:10px">進行は、この端末・ブラウザに自動保存されます。別の端末へ移すときは、書き出したファイルを読み込んでください。</p><div class="settings-buttons"><button class="secondary" data-action="export">セーブを書き出す</button><button class="secondary" data-action="import">セーブを読み込む</button></div><input class="hidden" id="save-file" type="file" accept="application/json,.json"><button class="quiet danger" data-action="reset-confirm">旅を最初からやり直す</button><div class="credits"><p>地図の輪郭はゲーム用に簡略化し、ステージ中の離島間隔は圧縮しています。</p><p>地形：<a href="https://www.gsi.go.jp/kankyochiri/gm_jpn.html" target="_blank" rel="noopener">国土地理院「地球地図日本」</a>を基にした<a href="https://github.com/dataofjapan/land" target="_blank" rel="noopener">dataofjapan/land</a>を加工。<br>庁舎位置：<a href="https://github.com/code4fukui/localgovjp" target="_blank" rel="noopener">code4fukui/localgovjp（CC0）</a>。<br><a href="./credits.html" target="_blank" rel="noopener">データの出典と利用条件</a></p></div></main>`,'settings');}
function help(){dialog('<p class="eyebrow">HOW TO PLAY</p><h2>形を使って、核を射抜く。</h2><ol class="help-list"><li>はじめにスワイプでパドルを回して、角度を決めます。北が上で0°。</li><li>下の操作帯を左右にスライド。発射ボタンで球を放ちます。</li><li>パドルも外周のブロックも、当たった辺の向きで球が反射します。島の隙間は通り抜けます。</li><li>県庁所在地の核をねらいます。沖縄はシールドなしで、1回当てればクリア。ほかの県は1回目でシールド、2回目で核が壊れてクリア。</li><li>黄色の「＋1」はボールを1個追加。水色の盾印は、画面下に1回だけ球を跳ね返すバリアを出します。</li><li>クリアした県を吸収して、沖縄県のパドルが大きくなります。</li></ol><p>PC：← → で移動、スペースで発射。沖縄は球数無制限。</p><button class="primary" data-action="close">閉じる</button>');}
function toMap(next=false){stopSpin();closeModal();if(game&&!['won','lost'].includes(game.status)&&!game.practice)saveCurrent();game=null;painter=null;paused=false;prepFinale=false;if(next){const open=availableIds(geo,save.cleared);selected=open[0]||47;selectedChapter=geo.get(selected).chapter;}renderMap();}
function retry(same=false,easy=false){const old=game;selected=old?.id||selected;angle=old?.angle??angle;save.angles[selected]=angle;if(easy)save.options.easy=true;save.current=null;persist();game=null;painter=null;paused=false;closeModal();prepFinale=false;if(same)startGame(false);else goPrep({skipStory:true,keepAngle:true});}
document.addEventListener('click',e=>{
 const a=e.target.closest('[data-action]'),p=e.target.closest('[data-pref]'),ch=e.target.closest('[data-chapter]'),book=e.target.closest('[data-book]'),replay=e.target.closest('[data-card-replay]');
 if(p&&view==='map'){selected=+p.dataset.pref;selectedChapter=geo.get(selected).chapter;renderMap();return;}
 if(ch&&view==='map'){selectedChapter=+ch.dataset.chapter;const available=availableIds(geo,save.cleared);selected=geo.chapters[selectedChapter].find(id=>available.includes(id))||geo.chapters[selectedChapter][0];renderMap();return;}
 if(book){showCard(+book.dataset.book);return;}if(replay){selected=+replay.dataset.cardReplay;closeModal();goPrep();return;}if(!a||a.disabled)return;
 switch(a.dataset.action){
  case 'map':toMap();break;case 'book':closeModal();renderBook();break;case 'settings':closeModal();renderSettings();break;case 'help':help();break;case 'close':closeModal();break;
  case 'prep':goPrep();break;case 'story-next':save.seenChapters.push(geo.get(selected).chapter);persist();goPrep({skipStory:true});break;
  case 'replace-run':save.current=null;persist();closeModal();goPrep();break;
  case 'reset-angle':stopSpin();angle=0;updateDial();break;case 'rotate-left':stopSpin();angle-=90;updateDial();break;case 'rotate-right':stopSpin();angle+=90;updateDial();break;
  case 'start':startGame();break;case 'practice':startGame(true);break;
  case 'practice-back':angle=game.angle;save.angles[selected]=angle;game=null;painter=null;paused=false;renderPrep();break;
  case 'launch':if(!paused)game?.launch();break;case 'pause':pauseDialog();break;
  case 'unpause':closeModal();paused=false;lastHUD='';acc=0;updateHUD();break;
  case 'game-map':toMap();break;case 'next-map':toMap(true);break;
  case 'resume':if(save.current){startGame(false,save.current);}break;
  case 'recall':closeModal();paused=false;game.recall();for(const ev of game.events.splice(0))handleGameEvent(ev);lastHUD='';updateHUD();break;
  case 'restart-confirm':dialog('<h2>最初から挑戦しますか？</h2><p>このステージの進行を戻し、パドルの角度を選び直します。獲得した県は残ります。</p><button class="primary" data-action="restart-yes">準備に戻る</button><button class="secondary" data-action="pause">ゲームに戻る</button>',{locked:true});break;
  case 'restart-yes':selected=game.id;save.current=null;save.angles[selected]=game.angle;persist();game=null;painter=null;paused=false;goPrep({skipStory:true});break;
  case 'retry':retry();break;case 'retry-same':retry(true);break;case 'retry-easy':retry(false,true);break;
  case 'ending':showEnding();break;case 'finale-prep':closeModal();game=null;painter=null;save.current=null;selected=1;goPrep({skipStory:true,finale:true});break;
  case 'export':{saveCurrent();const url=URL.createObjectURL(new Blob([JSON.stringify(save,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='kenken-breaker-save.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}
  case 'import':document.getElementById('save-file').click();break;
  case 'reset-confirm':dialog('<h2>旅の記録を消しますか？</h2><p>獲得した県、記録、中断データをすべて消して沖縄から始めます。必要なら先にセーブを書き出してください。</p><button class="secondary danger" data-action="reset-yes">すべて消してやり直す</button><button class="primary" data-action="close">戻る</button>');break;
  case 'reset-yes':save=NEW_SAVE();persist();selected=47;selectedChapter=0;toMap();break;
  case 'import-yes':if(window.pendingKenkenSave){save=window.pendingKenkenSave;delete window.pendingKenkenSave;persist();closeModal();selected=availableIds(geo,save.cleared)[0]||47;selectedChapter=geo.get(selected).chapter;renderSettings();toast('セーブデータを読み込みました。');}break;
 }
});
document.addEventListener('input',e=>{if(e.target.id==='angle-slider'){stopSpin();angle=+e.target.value;updateDial();}if(e.target.id==='sensitivity'){save.options.sensitivity=+e.target.value;document.getElementById('sensitivity-label').textContent=`${save.options.sensitivity.toFixed(1)}倍`;persist();}});
document.addEventListener('change',async e=>{
 const el=e.target;if(el.dataset.option){save.options[el.dataset.option]=el.checked;persist();if(el.dataset.option==='sound'&&el.checked)sound('launch');}
 if(el.id==='replay-shape'){replayOriginal=el.value==='original';updateDial();}
 if(el.id==='save-file'&&el.files[0]){try{const file=el.files[0];if(file.size>1_000_000)throw new Error('セーブファイルが大きすぎます。');const imported=validateSave(JSON.parse(await file.text()));if(imported.current){const c=imported.current;new Game(geo,{id:c.id,cleared:imported.cleared,paddleIds:validatedPaddleIds(c.paddleIds),angle:c.angle,easy:c.easy,finale:c.finale,snapshot:c});}window.pendingKenkenSave=imported;dialog(`<h2>セーブを読み込みますか？</h2><p>${imported.cleared.length}県をクリアした記録です。現在の進行を置き換えます。</p><button class="primary" data-action="import-yes">読み込む</button><button class="secondary" data-action="close">戻る</button>`);}catch(err){toast(`読み込めませんでした：${err.message}`);}el.value='';}
});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&view==='game'&&game&&!['won','lost'].includes(game.status)){paused=true;pauseDialog(true);}if(document.hidden)saveCurrent();});
window.addEventListener('pagehide',saveCurrent);
function frame(now){const dt=Math.min((now-(last||now))/1000,.06);last=now;if(view==='game'&&game){if(!paused){if(keys.has('ArrowLeft'))game.setTarget(game.targetX-dt*390);if(keys.has('ArrowRight'))game.setTarget(game.targetX+dt*390);acc+=dt;while(acc>=1/120&&!paused){game.tick(1/120);acc-=1/120;for(const e of game.events.splice(0))handleGameEvent(e);}if(now-lastSave>3000&&!game.practice){saveCurrent();lastSave=now;}}else acc=0;painter?.draw(dt);updateHUD();}requestAnimationFrame(frame);}
async function init(){try{const r=await fetch('./japan.json');if(!r.ok)throw new Error('地図を読み込めませんでした。');geo=new Geography(await r.json());if(geo.byId.size!==47)throw new Error('地図データが不完全です。');const open=availableIds(geo,save.cleared);selected=open[0]||47;selectedChapter=geo.get(selected).chapter;renderMap();requestAnimationFrame(frame);if(migratedRun){persist();toast('クリア済みの県は引き継ぎました。核とブロックの配置変更に伴い、中断中のステージは最初からになります。');}if(storageWarning)toast('保存データを読み込めませんでした。設定から保存先を確認してください。');}catch(e){root.innerHTML=`<main class="boot"><div class="brand-mark">47</div><h1>地図をひらけませんでした</h1><p>${esc(e.message)}</p><button class="secondary" style="width:auto" onclick="location.reload()">再読み込み</button></main>`;}}
init();
