(() => {
  'use strict';
  const STORAGE_KEY = 'jotei-no-yabo-save-v2';
  const LOCAL_RANKING_KEY = 'jotei-no-yabo-ranking-v1';
  const ONLINE_RANKING_URL = window.JOTEI_RANKING_URL || '';
  const app = document.querySelector('#app');
  const CARDS = {
    precog: { name: '先見の明', mark: '◉', timing: '投資先を選ぶ前', detail: '上位候補2業種と下位候補3業種を示します。' },
    stoploss: { name: '損切り命令', mark: '✂', timing: '投資決定前', detail: '下落時の総資産損失を最大-10%に抑えます。' },
    attack: { name: '総攻め', mark: '⚔', timing: '投資決定前', detail: 'ゲーム内騰落率を1.5倍にします。' },
    tenkabufu: { name: '天下布武', mark: '✦', timing: '投資決定前', detail: 'ゲーム内騰落率を2.0倍にします。' }
  };
  const FIXED_CARDS = Object.keys(CARDS);
  // プロトタイプ用の史実基準値。正式版では出典付きの実測データへ差し替える。
  const D = [
    ['1949','東京証券取引所再開','戦後の取引所再開。焼け跡から復興へ向かう企業に、少しずつ資金が戻り始めています。','復興局面では、生活と生産を支える産業へ資金が集まりました。',[['鉄鋼','⚙',18.6],['銀行・金融','▣',11.2],['建設','▤',14.8],['食品','◒',5.7],['運輸','➤',9.4]]],
    ['1950','朝鮮戦争特需','朝鮮半島の戦火を受け、特需の注文が国内企業へ流れ込んでいます。市場の熱気が急速に高まっています。','朝鮮戦争特需は、日本の生産設備と輸出産業の回復を後押ししました。',[['鉄鋼','⚙',42.3],['造船','⚓',38.1],['機械','⚒',30.7],['食品','◒',8.9],['小売','▥',6.1]]],
    ['1964','東京オリンピック','世界中の視線が東京へ。道路・鉄道・宿泊施設など、都市を整える需要が盛り上がっています。','五輪前後には都市インフラと消費の拡大が注目されました。',[['建設','▤',31.6],['不動産','⌂',27.4],['運輸','➤',20.2],['電機','◫',17.3],['食品','◒',6.8]]],
    ['1965','証券不況','景気の減速と株式市場の不安が広がり、強気の空気は急速に冷えています。資金を守る判断も必要です。','証券不況では市場全体が厳しい局面となり、現金待機の価値が高まりました。',[['銀行・金融','▣',-18.7],['鉄鋼','⚙',-21.4],['電機','◫',-10.6],['食品','◒',-4.8],['医薬品','✚',-2.9]]],
    ['1971','ニクソン・ショック','ドルと金の交換停止。為替制度の先行きが揺らぎ、輸出企業に警戒が広がっています。','通貨制度の変化は、輸出依存度の高い企業に大きく影響しました。',[['自動車','▰',-13.8],['電機','◫',-15.6],['商社','◇',-7.2],['小売','▥',2.6],['食品','◒',4.1]]],
    ['1973','第一次オイルショック','中東情勢の悪化で原油価格が急騰。国内では物価上昇と物不足が広がっています。','資源関連が注目される一方、燃料や原材料を多く使う産業には重荷となりました。',[['石油・資源','◉',28.9],['商社','◇',19.4],['自動車','▰',-18.6],['電機','◫',-13.2],['小売・食品','▥',3.1]]],
    ['1979','第二次オイルショック','再び原油価格が上昇。省エネ技術と燃費性能をめぐる競争が、企業の明暗を分け始めています。','エネルギー効率の改善が、産業競争力を左右するテーマになりました。',[['自動車','▰',16.4],['電機','◫',13.8],['石油・資源','◉',9.6],['商社','◇',6.2],['小売','▥',-4.7]]],
    ['1985','プラザ合意','主要国が為替の調整に合意。急速な円高が進み、輸出企業の利益見通しが揺れています。','円高は輸出産業の収益を圧迫する一方、内需系の追い風となる面もありました。',[['自動車','▰',-12.9],['電機','◫',-10.7],['不動産','⌂',19.8],['銀行・金融','▣',14.2],['小売','▥',8.5]]],
    ['1987','ブラックマンデー','米国市場の急落が世界を駆け巡ります。東京の寄り付きにも緊張が走り、投資家は対応を迫られています。','世界的な株価急落は、日本市場にも短期的な動揺をもたらしました。',[['銀行・金融','▣',-19.4],['不動産','⌂',-16.8],['電機','◫',-11.6],['食品','◒',-4.4],['医薬品','✚',-2.7]]],
    ['1989','バブル相場最高値','市場は連日の高値圏。土地と株はまだ上がるという声が、兜町を埋め尽くしています。','1989年末、日経平均は史上最高値を記録しました。高揚の裏には過熱への警戒もありました。',[['不動産','⌂',30.8],['銀行・金融','▣',24.5],['商社','◇',16.7],['電機','◫',10.2],['食品','◒',4.1]]],
    ['1990','バブル崩壊','株価は反落を続け、不動産と金融への不安が市場全体を覆っています。強気の資金繰りが重荷になります。','バブル崩壊後は資産価格の下落が長期化し、金融機関の不良債権問題へつながりました。',[['不動産','⌂',-38.6],['銀行・金融','▣',-31.4],['商社','◇',-19.8],['自動車','▰',-13.4],['食品','◒',-4.2]]],
    ['1997','金融危機','金融機関の経営不安が表面化。信用の揺らぎが、企業と投資家の行動を慎重にさせています。','金融危機では金融株が厳しい局面となり、守りの資産が選ばれやすくなりました。',[['銀行・金融','▣',-35.2],['不動産','⌂',-22.1],['商社','◇',-14.6],['通信','◌',5.7],['医薬品','✚',4.8]]],
    ['1999','ITバブル','インターネット関連企業への期待が加速。新しい技術が、既存の産業構造を変えると語られています。','IT関連への期待が株価を押し上げ、成長株への資金流入が目立ちました。',[['インターネット','◎',44.8],['通信','◌',32.6],['電機','◫',23.4],['自動車','▰',8.9],['銀行・金融','▣',5.2]]],
    ['2008','リーマンショック','米国の大手証券会社が破綻。世界の金融市場が連鎖的に下落し、国内企業にも急速に影響が広がります。','世界金融危機は日本株にも大きな下落をもたらし、内外の需要が大きく冷え込みました。',[['銀行・金融','▣',-41.5],['自動車','▰',-38.4],['電機','◫',-36.8],['商社','◇',-33.7],['医薬品','✚',-15.6]]],
    ['2013','金融緩和','大規模な金融緩和への期待で市場心理が転換。円安と企業収益の改善期待が株価を押し上げています。','金融緩和局面では輸出・不動産・金融など幅広い業種が注目されました。',[['自動車','▰',33.7],['不動産','⌂',29.1],['銀行・金融','▣',25.6],['電機','◫',22.4],['食品','◒',9.3]]],
    ['2020','コロナショック','感染症の拡大で人の移動と消費が急減。一方で、通信やデジタルサービスへの需要が急速に高まっています。','感染拡大は市場を急落させた一方、デジタル関連の需要を押し上げる転機にもなりました。',[['通信・ネット','◎',19.6],['ゲーム・娯楽','♜',17.2],['医薬品','✚',10.4],['小売・旅行','▥',-23.8],['運輸','➤',-28.6]]]
  ];
  const EVENT_IMAGES = { '1949':'1949-tse-reopening.webp', '1950':'1950-korean-boom.webp', '1964':'1964-tokyo-olympics.webp', '1965':'1965-securities-recession.webp', '1971':'1971-nixon-shock.webp', '1973':'1973-oil-shock.webp', '1979':'1979-second-oil.webp', '1985':'1985-plaza-accord.webp', '1987':'1987-black-monday.webp', '1989':'1989-bubble-peak.webp', '1990':'1990-bubble-collapse.webp', '1997':'1997-financial-crisis.webp', '1999':'1999-it-bubble.webp', '2008':'2008-lehman-shock.webp', '2013':'2013-monetary-easing.webp', '2020':'2020-covid-shock.webp' };
  const EVENTS = D.map(([year,title,news,memo,options]) => ({year,title,news,memo,image:EVENT_IMAGES[year],options:options.map(([name,icon,raw]) => ({name,icon,raw}))}));
  const formatMan = amount => {const oku=Math.floor(amount/10000),remainder=amount%10000;return oku?`${oku.toLocaleString('ja-JP')}億${remainder.toLocaleString('ja-JP')}万円`:`${amount.toLocaleString('ja-JP')}万円`;};
  const money = n => formatMan(Math.max(0,Math.floor(n/10000)));
  const signedMoney = n => {const amount=Math.floor(Math.abs(n)/10000);return `${n<0&&amount?'−':''}${formatMan(amount)}`;};
  const pct = n => `${n>0?'+':''}${n}%`;
  const trunc = n => n<0?Math.ceil(n):Math.floor(n);
  const xmur3 = s => { let h=1779033703^s.length; for(let i=0;i<s.length;i++){h=Math.imul(h^s.charCodeAt(i),3432918353);h=h<<13|h>>>19;} return()=>{h=Math.imul(h^h>>>16,2246822507);h=Math.imul(h^h>>>13,3266489909);return(h^=h>>>16)>>>0;};};
  const mulberry32 = a => () => {let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};
  const rng = seed => mulberry32(xmur3(seed)());
  const escapeHTML = v => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  let state;

  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
  function event(){return state.events[state.eventIndex];}
  function picked(){return state.selection==='cash'?null:event().options.find(o=>o.name===state.selection);}
  function available(id){return !state.usedCards.includes(id);}
  function startGame(){const seed=`${Date.now()}-${Math.random()}`;const random=rng(seed);state={seed,events:EVENTS.map(e=>({...e,options:e.options.map(o=>{const base=trunc(o.raw);const span=Math.floor(Math.abs(base)*.2);return{...o,base,game:base+Math.floor(random()*(span*2+1))-span};})})),eventIndex:0,assets:10000000,peakAssets:10000000,usedCards:[],currentEffect:null,selection:null,allocation:null,phase:'intro',history:[]};save();renderEventIntro();}
  function topTwo(){return[...event().options].sort((a,b)=>b.base-a.base).slice(0,2).map(o=>o.name);}
  function calculation(option,allocation,effect){if(!option)return{rawReturn:0,assetChange:0,nextAssets:state.assets};let rawReturn=option.game;if(effect==='attack')rawReturn=trunc(rawReturn*1.5);if(effect==='tenkabufu')rawReturn=trunc(rawReturn*2);let assetChange=rawReturn*allocation;if(effect==='stoploss'&&assetChange<-10)assetChange=-10;const nextAssets=Math.floor(state.assets*(1+assetChange/100));return{rawReturn,assetChange,nextAssets};}
  function renderTitle(){app.innerHTML=`<section class="game-page title-page"><img class="hero-art" src="assets/empress-key-visual.webp" alt=""><header class="topbar"><div class="wordmark"><strong>女帝の野望</strong><span>KABUTOCHO CHRONICLE</span></div><button class="top-action" data-action="howto">遊び方</button></header><div class="title-wrap"><div class="title-panel"><span class="eyebrow">日本株・歴史戦略遊戯</span><h1>女帝の野望</h1><p class="lead">戦後の焼け跡から、現代の最高値まで。史実を手がかりに国内業種へ資金を投じ、兜町の頂へ登り詰めよ。</p><div class="title-points"><span>全16局面</span><span>現金＋国内5業種</span><span>固定4カード</span><span>オンラインスコア</span></div><button class="start-button" data-action="begin">女帝として相場に臨む</button><small class="tiny">※これは歴史を題材にしたフィクションのゲームです。実際の投資判断を目的としません。</small></div></div></section>`;}
  function renderEventIntro(){const e=event();app.innerHTML=`<section class="game-page event-intro-page"><img class="event-intro-art" src="assets/events/${e.image}" alt=""><header class="topbar event-intro-topbar"><div class="wordmark"><strong>女帝の野望</strong><span>HISTORICAL EVENT</span></div><button class="top-action" data-action="title">タイトルへ</button></header><button class="event-intro-dismiss" data-action="dismiss-intro" aria-label="タップして投資画面へ進む"><span class="event-intro-copy"><span class="event-year">HISTORICAL EVENT / ${e.year}</span><h1>${e.title}</h1><p>${e.news}</p><span class="event-intro-tap">タップして相場へ <b>›</b></span></span></button></section>`;}
  function renderPlay(){
    const e=event(),choice=picked(),cash=state.selection==='cash',active=state.currentEffect?CARDS[state.currentEffect]:null,progress=Math.round((state.eventIndex/state.events.length)*100);
    const choices=[`<button class="choice ${cash?'selected':''}" data-choice="cash"><span class="choice-icon">▣</span><span class="choice-name">現金</span></button>`,...e.options.map(o=>`<button class="choice ${state.selection===o.name?'selected':''}" data-choice="${escapeHTML(o.name)}"><span class="choice-icon">${o.icon}</span><span class="choice-name">${o.name}</span>${state.currentEffect==='precog'?`<i class="choice-hint ${topTwo().includes(o.name)?'':'low'}">${topTwo().includes(o.name)?'上位候補':'下位候補'}</i>`:''}</button>`)].join('');
    const cards=FIXED_CARDS.map(id=>{const c=CARDS[id],returnCard=['attack','tenkabufu','stoploss'].includes(id),activeCard=state.currentEffect===id,disabled=(!available(id)&&!activeCard)||(Boolean(state.currentEffect)&&!activeCard)||(cash&&returnCard&&!activeCard)||(activeCard&&id==='precog');return`<button class="in-play-card ${activeCard?'active':''}" data-card="${id}" ${disabled?'disabled':''}><span class="card-mark">${c.mark}</span><span><strong>${c.name}</strong><small>${c.timing}</small></span></button>`;}).join('');
    const canConfirm=cash||(choice&&state.allocation);
    const decision=cash?'<div class="cash-status">現金で待機（0%）</div>':choice?`<button class="allocation-button ${state.allocation===1?'selected':''}" data-allocation="1"><b>現物取引 100%</b><small>保有資金をすべて投資</small></button><button class="allocation-button credit ${state.allocation===3?'selected':''}" data-allocation="3"><b>信用取引 300%</b><small>借入で3倍の大勝負</small></button>`:'<div class="cash-status">投資先を選択してください</div>';
    app.innerHTML=`<section class="game-page play-screen"><img class="hero-art" src="assets/empress-key-visual.webp" alt=""><header class="topbar"><div class="wordmark"><strong>女帝の野望</strong><span>TURN ${state.eventIndex+1} / ${state.events.length}</span></div><div class="top-actions"><button class="top-action" data-action="title">タイトルへ</button><button class="top-action" data-action="howto">遊び方</button></div></header><main class="compact-play"><div class="hud"><div class="hud-item"><span class="hud-label">総資産</span><span class="hud-value">${money(state.assets)}</span></div><div class="hud-item"><span class="hud-label">現在の局面</span><span class="hud-value">${e.year}年</span></div><div class="hud-item"><span class="hud-label">残り局面</span><span class="hud-value">${state.events.length-state.eventIndex}</span><span class="turn-meter" aria-label="進行度 ${progress}%"><i style="width:${progress}%"></i></span></div></div><article class="compact-event"><img class="event-art" src="assets/events/${e.image}" alt=""><div class="event-copy"><span class="event-year">HISTORICAL EVENT / ${e.year}</span><h2 class="event-title">${e.title}</h2><p class="event-news">${e.news}</p></div></article><section class="compact-choice"><h3 class="choice-heading">今、何を保有する？</h3><div class="choice-grid">${choices}</div></section><section class="compact-cards"><h3>女帝カード</h3><div class="card-row">${cards}</div><div class="active-card-message">${active?state.currentEffect==='precog'?`「${active.name}」を使用済み — 上位・下位候補を確認したため解除できません。`:`「${active.name}」を使用中 — もう一度タップすると選択解除します。`:'各カードは1ゲームに1回。投資比率に関係なく使えます。'}</div></section><section class="compact-decision">${decision}<button class="confirm-button ${cash?'cash-ready':''}" data-action="confirm" ${canConfirm?'':'disabled'}>投資を決定</button></section></main></section>`;
  }
  function useCard(id){if(state.currentEffect===id){if(id==='precog')return;state.currentEffect=null;state.usedCards=state.usedCards.filter(cardId=>cardId!==id);save();renderPlay();return;}if(!available(id)||state.currentEffect)return;if(state.selection==='cash'&&['attack','tenkabufu','stoploss'].includes(id))return;state.currentEffect=id;state.usedCards.push(id);save();renderPlay();}
  function confirm(){const option=picked(),allocation=state.selection==='cash'?0:state.allocation;if(state.selection!=='cash'&&(!option||!allocation))return;const calc=calculation(option,allocation,state.currentEffect);state.pending={option,allocation,effect:state.currentEffect,beforeAssets:state.assets,...calc};state.assets=calc.nextAssets;state.peakAssets=Math.max(state.peakAssets,state.assets);if(state.assets<0){state.phase='gameover';save();renderGameOver();return;}state.phase='result';save();renderResult();}
  function renderResult(){const e=event(),p=state.pending,rows=[{name:'現金',icon:'▣',game:0},...e.options].sort((a,b)=>b.game-a.game).map((o,i)=>{const mine=(p.option&&o.name===p.option.name)||(!p.option&&o.name==='現金'),cls=o.game>0?'positive':o.game<0?'negative':'flat';return`<div class="return-row ${mine?'player':''}"><span>${i+1}</span><span>${o.icon} ${o.name}${mine?'　← あなた':''}</span><b class="${cls}">${pct(o.game)}</b></div>`;}).join('');const c=p.assetChange>0?'victory':p.assetChange<0?'loss':'neutral';const detail=p.option?`${p.option.name} ${pct(p.rawReturn)} ／ ${p.allocation===3?'信用取引 300%':'現物取引 100%'}`:'現金で待機 0%';app.innerHTML=`<section class="game-page"><header class="topbar"><div class="wordmark"><strong>女帝の野望</strong><span>RESULT ${state.eventIndex+1} / ${state.events.length}</span></div><button class="top-action" data-action="title">タイトルへ</button></header><div class="result-wrap"><section class="result-hero ${c}"><p class="result-kicker">${e.year}年　${e.title}</p><h2 class="result-title">${p.assetChange>0?'大勝利':p.assetChange<0?'敗走':'籠城'}</h2><div class="result-change ${c}">${p.assetChange>0?'+':''}${p.assetChange}%</div><p class="result-desc">${detail}<br>${p.effect?`「${CARDS[p.effect].name}」を使用`:'女帝カードは未使用'}<br>資産: ${money(p.beforeAssets)} → <b>${money(state.assets)}</b></p></section><div class="result-grid"><section class="result-table"><h3>今局面の結果</h3>${rows}</section><section class="memo-panel"><h3>史実メモ</h3><p>${e.memo}</p></section></div><div class="result-actions"><button class="next-button" data-action="next">${state.eventIndex===state.events.length-1?'最終決算へ':'次の局面へ'}</button></div></div></section>`;}
  function renderGameOver(){const e=event(),p=state.pending,detail=p.option?`${p.option.name} ／ ${p.allocation===3?'信用取引 300%':'現物取引 100%'}`:'現金で待機 0%';app.innerHTML=`<section class="game-page game-over-page"><img class="hero-art" src="assets/game-over-visual.webp" alt=""><header class="topbar"><div class="wordmark"><strong>女帝の野望</strong><span>MARKET COLLAPSE</span></div><button class="top-action" data-action="title">タイトルへ</button></header><main class="game-over-wrap"><section class="game-over-panel"><span class="eyebrow">${e.year}年　${e.title}</span><h1>GAME OVER</h1><p>信用取引の損失で、運用資金が尽きました。</p><div class="debt-value">${signedMoney(state.assets)}</div><p class="game-over-detail">最終判断：${detail}<br>今回の資産変化：${p.assetChange}%</p><button class="start-button" data-action="restart">最初から再起する</button><button class="subtle-button" data-action="title">タイトルへ戻る</button></section></main></section>`;}
  function next(){const p=state.pending;state.history.push({event:event().title,assets:state.assets,allocation:p.allocation,change:p.assetChange,effect:p.effect});state.eventIndex++;state.selection=null;state.allocation=null;state.currentEffect=null;state.pending=null;if(state.eventIndex===state.events.length){state.phase='final';save();renderFinal();return;}state.phase='intro';save();renderEventIntro();}
  function titleFor(assets){if(assets>=65000000)return'天下無双の女帝';if(assets>=35000000)return'相場の女王';if(assets>=18000000)return'投資大名';if(assets>=10000000)return'相場の姫';return'兜町の見習い';}
  function localScores(){try{return JSON.parse(localStorage.getItem(LOCAL_RANKING_KEY)||'[]');}catch{return[];}}
  function setLocalScores(scores){localStorage.setItem(LOCAL_RANKING_KEY,JSON.stringify(scores.slice(0,20)));}
  function renderAssetTrend(){const grid=document.querySelector('.record-grid');if(!grid||document.querySelector('.asset-trend'))return;const opening=10000000,series=[{year:'1949',assets:opening},...state.history.map((entry,index)=>({year:state.events[index]?.year||'',assets:entry.assets}))],W=660,H=210,L=17,R=17,T=23,B=34,min=Math.min(...series.map(point=>point.assets)),max=Math.max(...series.map(point=>point.assets)),spread=Math.max(max-min,Math.max(max*.04,1)),floor=Math.max(0,min-spread*.12),ceiling=max+spread*.12,plotH=H-T-B,plotW=W-L-R,points=series.map((point,index)=>({x:L+index/(series.length-1)*plotW,y:T+(ceiling-point.assets)/(ceiling-floor)*plotH,...point})),line=points.map((point,index)=>`${index?'L':'M'}${point.x.toFixed(1)} ${point.y.toFixed(1)}`).join(' '),area=`${line} L${points.at(-1).x.toFixed(1)} ${H-B} L${points[0].x.toFixed(1)} ${H-B} Z`,peak=points.reduce((best,point)=>point.assets>best.assets?point:best,points[0]),gridLines=[.25,.5,.75].map(ratio=>{const y=T+plotH*ratio;return`<line x1="${L}" y1="${y.toFixed(1)}" x2="${W-R}" y2="${y.toFixed(1)}"/>`;}).join('');grid.insertAdjacentHTML('beforebegin',`<section class="asset-trend"><div class="trend-heading"><div><span>ASSET HISTORY</span><h3>資産の推移</h3></div><b>最高 ${money(peak.assets)}</b></div><svg class="trend-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="1949年から2020年までの総資産推移グラフ"><defs><linearGradient id="trend-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#e8c274" stop-opacity=".42"/><stop offset="1" stop-color="#e8c274" stop-opacity="0"/></linearGradient></defs><g class="trend-grid">${gridLines}</g><path class="trend-area" d="${area}"/><path class="trend-line" d="${line}"/><circle class="trend-peak" cx="${peak.x.toFixed(1)}" cy="${peak.y.toFixed(1)}" r="5"/><circle class="trend-final" cx="${points.at(-1).x.toFixed(1)}" cy="${points.at(-1).y.toFixed(1)}" r="4"/><text x="${L}" y="${H-10}">${series[0].year}</text><text x="${W-R}" y="${H-10}" text-anchor="end">${points.at(-1).year}</text></svg><div class="trend-summary"><span>開始　<b>${money(opening)}</b></span><span>最終　<b>${money(state.assets)}</b></span></div></section>`);}
  function renderLeaders(scores,mode){const target=document.querySelector('#leaderboard');if(!target)return;const list=scores.sort((a,b)=>b.score-a.score).slice(0,10);target.innerHTML=`<h3>${mode==='online'?'全国 女帝ランキング':'この端末のランキング'}</h3>${list.length?list.map((s,i)=>`<div class="leader-row"><span>${i+1}</span><b>${escapeHTML(s.name)}</b><span>${money(Number(s.score))}</span></div>`).join(''):'<div class="leader-status">まだ記録がありません。</div>'}`;}
  async function loadLeaderboard(){renderAssetTrend();const target=document.querySelector('#leaderboard');if(!target)return;if(!ONLINE_RANKING_URL){renderLeaders(localScores(),'local');return;}target.innerHTML='<div class="leader-status">全国ランキングを読み込み中…</div>';try{const r=await fetch(ONLINE_RANKING_URL,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error();const data=await r.json();renderLeaders(Array.isArray(data)?data:data.scores||[],'online');document.querySelector('#ranking-note').textContent='全国の女帝たちとスコアを競えます。';}catch{renderLeaders(localScores(),'local');document.querySelector('#ranking-note').textContent='オンラインランキングに接続できないため、この端末の記録を表示しています。';}}
  function renderFinal(){const wins=state.history.filter(x=>x.change>0).length,full=state.history.filter(x=>x.allocation===1).length,credit=state.history.filter(x=>x.allocation===3).length,score=Math.floor(state.assets);app.innerHTML=`<section class="game-page"><img class="hero-art" src="assets/empress-key-visual.webp" alt=""><header class="topbar"><div class="wordmark"><strong>女帝の野望</strong><span>FINAL AUDIENCE</span></div><button class="top-action" data-action="title">タイトルへ</button></header><div class="final-wrap"><div class="final-emblem">✦</div><p class="eyebrow">最終決算</p><h2>${titleFor(state.assets)}</h2><p class="final-sub">1949年から2020年まで、あなたは市場の荒波を越えました。</p><div class="final-assets">${money(state.assets)}</div><p class="final-rank">女帝スコア　${money(score)}</p><div class="record-grid"><div class="record"><span>最高資産</span><b>${money(state.peakAssets)}</b></div><div class="record"><span>現物取引 100%</span><b>${full} 回</b></div><div class="record"><span>信用取引 300%</span><b>${credit} 回</b></div><div class="record"><span>利益を得た局面</span><b>${wins} / ${state.events.length}</b></div></div><form class="ranking-form" id="score-form"><input name="name" maxlength="12" required autocomplete="nickname" placeholder="名前を入力（12文字まで）"><button type="submit">スコア登録</button></form><p class="ranking-note" id="ranking-note">ランキングを読み込み中…</p><section class="leaderboard" id="leaderboard"></section><button class="start-button" data-action="restart">もう一度、天下を目指す</button></div></section>`;loadLeaderboard();}
  async function submitScore(form){const input=form.elements.name,name=input.value.trim();if(!name)return;const score=Math.floor(state.assets),entry={name,score,playedAt:new Date().toISOString()};const note=document.querySelector('#ranking-note');form.querySelector('button').disabled=true;try{if(ONLINE_RANKING_URL){const r=await fetch(ONLINE_RANKING_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(entry)});if(!r.ok)throw new Error();note.textContent='全国ランキングへ登録しました。';await loadLeaderboard();}else{const scores=[...localScores(),entry].sort((a,b)=>b.score-a.score);setLocalScores(scores);note.textContent='この端末のランキングへ登録しました。全国ランキングは接続先の設定後に有効になります。';renderLeaders(scores,'local');}}catch{note.textContent='登録できませんでした。通信状態を確認して再度お試しください。';}finally{form.querySelector('button').disabled=false;}}
  function howto(){const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-label="遊び方"><h2>遊び方</h2><p>各局面で、<b>現金または国内5業種</b>から1つを選びます。現金なら0%、業種を選ぶなら100%か信用取引300%です。</p><ul><li>相場は史実基準騰落率を中心に、絶対値の20%以内で1%刻みに変動します。</li><li>カードは「先見の明」「損切り命令」「総攻め」「天下布武」の4枚固定です。各1回、同じ局面では1枚まで使えます。</li><li>総攻めと天下布武は、100%投資でも信用取引300%でも使えます。</li><li>資金がマイナスになった時点でゲームオーバーです。</li><li>最終資産額が女帝スコアです。</li></ul><button data-action="closemodal">閉じる</button></section>`;document.body.append(modal);}
  app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(a==='howto'){howto();return;}if(a==='title'){localStorage.removeItem(STORAGE_KEY);renderTitle();return;}if(a==='begin'){startGame();return;}if(a==='dismiss-intro'){state.phase='play';save();renderPlay();return;}if(a==='confirm'){confirm();return;}if(a==='next'){next();return;}if(a==='restart'){localStorage.removeItem(STORAGE_KEY);startGame();return;}if(b.dataset.choice){state.selection=b.dataset.choice;state.allocation=null;if(state.selection==='cash'&&state.currentEffect&&state.currentEffect!=='precog'){state.usedCards=state.usedCards.filter(x=>x!==state.currentEffect);state.currentEffect=null;}save();renderPlay();return;}if(b.dataset.allocation){state.allocation=Number(b.dataset.allocation);save();renderPlay();return;}if(b.dataset.card){useCard(b.dataset.card);}});
  app.addEventListener('submit',e=>{if(e.target.id==='score-form'){e.preventDefault();submitScore(e.target);}});
  document.body.addEventListener('click',e=>{if(e.target.dataset.action==='closemodal'||e.target.classList.contains('modal-backdrop'))e.target.closest('.modal-backdrop')?.remove();});
  try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved&&saved.phase&&saved.events){state=saved;saved.phase==='intro'?renderEventIntro():saved.phase==='result'&&saved.pending?renderResult():saved.phase==='final'?renderFinal():saved.phase==='gameover'&&saved.pending?renderGameOver():renderPlay();}else renderTitle();}catch{renderTitle();}
})();
